In [1]:
import yaml

In [11]:
fname = 'default.yaml'
with open(fname, 'r') as stream:
    try:
        # Converts yaml document to python object
        d=yaml.safe_load(stream)

        # Printing dictionary
        print(d)
    except yaml.YAMLError as e:
        print(e)

{'algorithm': 'DQN', 'configuration': {'train_model': True, 'start_from_previous_session': False, 'save_data': False, 'generate_plots': False, 'save_aggregate_rewards': True, 'continue_training': False}, 'environment_settings': {'seeds': '1000 * thread_num', 'num_of_agents': 75, 'num_of_chargers': 3, 'make': 0, 'model': 0, 'max_charge': 100000, 'coords': ['(43.02120034946083', '-81.28349087468504)', '(43.004969336049854', '-81.18631870502043)', '(42.95923445066671', '-81.26016049362336)', '(42.98111190139387', '-81.30953935839466)', '(42.9819404397449', '-81.2508736429095)'], 'radius': 20, 'starting_charge': ['6000 for agent in range(num_of_agents)']}}


In [10]:
from yaml import load
try:
    from yaml import CLoader as Loader
except ImportError:
    from yaml import Loader

stream = open(fname, 'r')
dictionary = yaml.safe_load(stream)
for key, value in dictionary.items():
    print (key + " : " + str(value))

algorithm : DQN
configuration : {'train_model': True, 'start_from_previous_session': False, 'save_data': False, 'generate_plots': False, 'save_aggregate_rewards': True, 'continue_training': False}
environment_settings : {'seeds': '1000 * thread_num', 'num_of_agents': 75, 'num_of_chargers': 3, 'make': 0, 'model': 0, 'max_charge': 100000, 'coords': ['(43.02120034946083', '-81.28349087468504)', '(43.004969336049854', '-81.18631870502043)', '(42.95923445066671', '-81.26016049362336)', '(42.98111190139387', '-81.30953935839466)', '(42.9819404397449', '-81.2508736429095)'], 'radius': 20, 'starting_charge': ['6000 for agent in range(num_of_agents)']}


In [17]:
d['configuration']['train_model']

True

In [1]:
import torch
import numpy as np

In [2]:
rng = np.random.default_rng(seed=1234)
rng.random((3,3))

array([[0.97669977, 0.38019574, 0.92324623],
       [0.26169242, 0.31909706, 0.11809123],
       [0.24176629, 0.31853393, 0.96407925]])

In [3]:
rng.random(5)

array([0.2636498 , 0.44100612, 0.60987081, 0.8636213 , 0.86375767])

In [4]:
starting = 6000
# starting_charge[agent] += 1000 * random.randrange(-1, 1)
#
random_charged_level = starting + 2000*(rng.random(3)-0.5)
random_charged_level


array([6349.7626267 , 6319.74869592, 6471.51539663])

In [6]:
rng.integers(low=0, high=10000,size=5)

array([7386, 2227, 8670, 1720, 7887])